CREATE TABLE PRODUCTO (
    ID_PRODUCTO    NUMBER(10)      NOT NULL,
    CODIGO         VARCHAR2(20)    NOT NULL,
    NOMBRE         VARCHAR2(120)   NOT NULL,
    MARCA          VARCHAR2(60)    NOT NULL,
    MODELO         VARCHAR2(60)    NOT NULL,
    PRECIO         NUMBER(10,2)    NOT NULL,
    STOCK          NUMBER(10)      NOT NULL,
    ESTADO         CHAR(1)         DEFAULT 'A' NOT NULL,
    FECHA_CREACION TIMESTAMP       DEFAULT SYSTIMESTAMP,
    FECHA_MODIF    TIMESTAMP,
    CONSTRAINT PK_PRODUCTO         PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT UK_PRODUCTO_CODIGO  UNIQUE (CODIGO),
    CONSTRAINT CK_PRODUCTO_ESTADO  CHECK (ESTADO IN ('A', 'I')),
    CONSTRAINT CK_PRODUCTO_PRECIO  CHECK (PRECIO >= 0),
    CONSTRAINT CK_PRODUCTO_STOCK   CHECK (STOCK >= 0)
);

CREATE INDEX IDX_PRODUCTO_MARCA_MODELO ON PRODUCTO (MARCA, MODELO);
