CREATE SEQUENCE SEQ_PRODUCTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_PRODUCTO_BI
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRODUCTO IS NULL THEN
        :NEW.ID_PRODUCTO := SEQ_PRODUCTO.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
END;
/
