INSERT INTO PRODUCTO (CODIGO, NOMBRE, MARCA, MODELO, PRECIO, STOCK)
VALUES ('PROD-001', 'Laptop UltraSlim 15', 'Dell', 'Inspiron 15 3000', 2499.99, 25);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, MARCA, MODELO, PRECIO, STOCK)
VALUES ('PROD-002', 'Smartphone Galaxy S24', 'Samsung', 'Galaxy S24', 3199.00, 40);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, MARCA, MODELO, PRECIO, STOCK)
VALUES ('PROD-003', 'Monitor 4K 27"', 'LG', 'UltraFine 27UN83A', 1350.50, 15);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, MARCA, MODELO, PRECIO, STOCK)
VALUES ('PROD-004', 'Teclado Mecánico RGB', 'Logitech', 'G Pro X', 450.00, 60);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, MARCA, MODELO, PRECIO, STOCK)
VALUES ('PROD-005', 'Mouse Inalámbrico Ergonómico', 'Logitech', 'MX Master 3S', 320.00, 75);

COMMIT;
